# Generated by Django 3.2.6 on 2021-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=25, verbose_name='User Id')),
                ('Button_name', models.CharField(max_length=100, verbose_name='Button name')),
                ('No_Calls', models.IntegerField(default=0, verbose_name='No of Calls')),
            ],
        ),
    ]
